version: '3.8'

services:
  frontend:
    build: ./Frontend
    ports:
      - '3000:80'
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001/api
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./Backend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data: 